// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtBo_NIFe6jumlYx9Vfiu_kdCP7aEyA6U',
    appId: '1:608661164651:web:23699b0aed8bd069bbd72e',
    messagingSenderId: '608661164651',
    projectId: 'gps-meeting-app',
    authDomain: 'gps-meeting-app.firebaseapp.com',
    storageBucket: 'gps-meeting-app.firebasestorage.app',
    measurementId: 'G-QFK01XERL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeVz0Llb___rtUddL4spzJXjVDkB_oPFs',
    appId: '1:608661164651:android:5c6cb8f7163e8dd6bbd72e',
    messagingSenderId: '608661164651',
    projectId: 'gps-meeting-app',
    storageBucket: 'gps-meeting-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYXIsr0OGkZdNKKsNPqHpEPHyDf8w3XqA',
    appId: '1:608661164651:ios:33f438d4b37ed103bbd72e',
    messagingSenderId: '608661164651',
    projectId: 'gps-meeting-app',
    storageBucket: 'gps-meeting-app.firebasestorage.app',
    iosBundleId: 'com.gpsmeetingapp.gpsMeetingApp',
  );
}
